[project]
name = "kverus"
version = "0.1.0"
description = "Scalable and Resilient Formal Verification Proof Generation for Rust Code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.2",
    "tree-sitter>=0.25.2",
    "tree-sitter-verus",
]

[dependency-groups]
dev = ["requests>=2.32.4", "deptry>=0.23.1", "pre-commit>=4.3.0"]

[tool.uv]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[tool.uv.sources]
tree-sitter-verus = { path = "deps/tree-sitter-verus" }

[tool.deptry]
exclude = ["\\.venv", "deps"]
